### ISSUE TITLE
Improve logging or return error

### ISSUE THREAD

**Issue by doskabouter** [yartat/MP-MediaInfo#13]
When trying to get the info from a corrupted file, there's nothing in the log, and also no property on the MediaInfoWrapper instance that can be checked for errors.

**Comment by andrewjswan** [comment]
@yartat ... :)

**Comment by doskabouter** [comment]
bump?

**Comment by yartat** [comment]
I updated the sample with `ILogger` implementation for ASP.NET Core.

**Comment by yartat** [comment]
I close this issue. If you has any suggestions, please create a new issue.
