### ISSUE TITLE
Debian.10 is not a supported runtime for MediaInfo.Core.Native

### ISSUE THREAD

**Issue by NickDrouin** [yartat/MP-MediaInfo#16]
The native builds [do exist for Debian 10 (Buster)](https://packages.debian.org/buster/libmediainfo0v5), I would imagine this would be a packaging change.  I can't find the actual repo for MediaInfo.Core.Native but assume that you maintain it?

Debian.10 is the current linux runtime for Azure Functions, and would unblock the use of MedaiInfo.Wrapper.Core there.  

Another solid addition for native runtimes for container scenarios would be Alpine, which [also has a native package](https://pkgs.alpinelinux.org/package/edge/community/x86_64/libmediainfo).

**Comment by yartat** [comment]
I've updated MediaInfo.Core.Native to 19.9.1. Just update it in solution https://www.nuget.org/packages/MediaInfo.Core.Native/19.9.1
