### ISSUE TITLE
Native MediaInfo library is not staticlly linked in Wrapper.Core under Ubuntu

### ISSUE THREAD

**Issue by ransagy** [yartat/MP-MediaInfo#17]
NOTE; I'm not sure if this is a bug report or a feature request, So i'll try to be clear about what im getting and what im expecting either way.

When running under Ubuntu 18.04 LTS and using the Wrapper.Core package, libmediainfo.so is being loaded from the runtimes/ubuntu-18.04-x64 folder.

On a fresh Ubuntu 18.04 machine, loading of the native libmediainfo.so library fails. Inspection shows it is not statically linked, requiring the installation of libzen(0v5) and libmms(0) before it works.

Is that intended? Is it possible to provide a statically linked version or perhaps provide a readme that indicates this?

**Comment by yartat** [comment]
U are right. I didn't add third party libraries to nuget package MediaInfo.Core.Native. I guess any producer of the service or application should independently make the correct installation package indicating all dependent packages. The only one exclusion is Windows, because Windows hasn't good package manager.

**Comment by ransagy** [comment]
Perhaps its worth adding a note about it in the NuGet page and/or in the README in this repo so it would be clearer that those libraries are needed, Rather than people finding out at runtime.

**Comment by yartat** [comment]
Good point. I'll update README

**Comment by yartat** [comment]
README.md has been updated at https://github.com/yartat/MP-MediaInfo/commit/ebe6efa95443874d1e41647ec1b605a6b443c078
