### ISSUE TITLE
Change Error to Warning for TV, Radio etc

### ISSUE THREAD

**Issue by andrewjswan** [yartat/MP-MediaInfo#18]
Можно поменять уровень ошибки на Warning или Info в этой строке ...
https://github.com/yartat/MP-MediaInfo/blob/master/MediaInfo.Wrapper/MediaInfoWrapper.cs#L130

**Comment by andrewjswan** [comment]
Или может вообще Debug ...

**Comment by yartat** [comment]
Release 19.09.2 done

**Comment by andrewjswan** [comment]
Thanks ...

**Comment by andrewjswan** [comment]
Plz update nuget package ...

**Comment by andrewjswan** [comment]
Thanks i found ...
