### ISSUE TITLE
MediaInfo.Native package not correct ?

### ISSUE THREAD

**Issue by StefH** [yartat/MP-MediaInfo#2]
I'm unable to use the MediaInfo.Wrapper because the MediaInfo.Native package is not currently working.
I think that:

1] the targets file from MediaInfo.Native is not appended to the project where I import this NuGet.

2] Also If I try to add the import manually: <Import Project="....\packages\MediaInfo.Native.0.7.91\build\native\MediaInfo.Native.targets" Condition="Exists('....\packages\MediaInfo.Native.0.7.91\build\native\MediaInfo.Native.targets')" />
I see that the dll files are copied to the output (Debug/Release) folder into two sub-folders ("x64" and "x86").
But when running some code, the dll's are not found.

**Comment by StefH** [comment]
For more details see https://github.com/StefH/WebDAV-AudioPlayer/blob/master/src/WebDAV-AudioPlayer/WebDAV-AudioPlayer.csproj#L193 where I just use the copy command in the postbuild to copy all dll files to the output folder.

**Comment by yartat** [comment]
I see. I will fix it today.
