### ISSUE TITLE
Revise license

### ISSUE THREAD

**Issue by Deadpikle** [yartat/MP-MediaInfo#21]
Hi,

This repo says it is licensed under the MIT license. However, it is clearly distributing GPL-licensed files, as evidenced by the headers at the top of source files.

Please revise the license on this repo to make it clear to users that the code they are using is GPL, not MIT.

Examples (very random sampling):

https://github.com/yartat/MP-MediaInfo/blob/ebe6efa95443874d1e41647ec1b605a6b443c078/MediaInfo.Wrapper/MediaInfoWrapper.cs#L6-L9

https://github.com/yartat/MP-MediaInfo/blob/ebe6efa95443874d1e41647ec1b605a6b443c078/MediaInfo.Wrapper/Model/BitrateMode.cs#L6-L9

https://github.com/yartat/MP-MediaInfo/blob/ebe6efa95443874d1e41647ec1b605a6b443c078/MediaInfo.Wrapper/LanguageHelper.cs#L6-L9

Thanks.

**Comment by yartat** [comment]
Fixed in 20.09 Release
