### ISSUE TITLE
MediaInfoWrapper should be JSON serializable / deserializable

### ISSUE THREAD

**Issue by MrRickwi** [yartat/MP-MediaInfo#24]
For working with information extracted from a media file within e.g. REST APIs, it is required to have JSON serialization/deserialization capabilities. Principally, the class is serializable and deserializable, however, all read-only properties like BestVideoStream, Duration, Framerate etc. are empty after deserialization. The method SetupProperties is a) private and b) requires some information which is obiously not there when deserializing the class. In first step it would help to make the method public and at least to be able to handle mediaInfo == null condition.

**Comment by yartat** [comment]
I prepared ASP.NET Core sample in docker to show how to fix the issue. See `/Samples/ApiSample`

**Comment by MrRickwi** [comment]
Thanks!
