### ISSUE TITLE
Add listing attachments from mkv file

### ISSUE THREAD

**Issue by DrDevinRX** [yartat/MP-MediaInfo#26]
Can you add getting the attachments `General;%Attachments%` to the wrapper?

**Comment by yartat** [comment]
Could you provide `.mkv` examples for testing?

**Comment by DrDevinRX** [comment]
@yartat Hi, here is a link to a file with attachments: https://drive.google.com/file/d/1RCRqL8J0idv3ranvl8No-GVbPEsFOp7L/view?usp=sharing

From MediaInfo, I would like the attachments field in General:

![image](https://user-images.githubusercontent.com/22141991/118653909-01610b00-b7b6-11eb-9d02-2ea77fb32757.png)

**Comment by yartat** [comment]
Thanks a lot!

**Comment by yartat** [comment]
I added `Attachments`, `IsStreamable`, `WritingApplication`, `WritingLibrary`. They are available in version 20.3.2.
