### ISSUE TITLE
Usage in Docker with webapi

### ISSUE THREAD

**Issue by hwmaat** [yartat/MP-MediaInfo#28]
Using this nice wrapper  in a .NET Core WebApi projects and all is good when running on the machine . Also works great when running on AWS in an elastic beans. No problems there.

Now I created a docker image and this is where it goes wrong:
The file filePath get's created as something like _/tmp/adfexssd.tmp_
It is stored in that directory as well. But the info returned is empty, just nulls and zero's.

            IFormFile file = commercialAsset.UploadFile;
            var filePath = Path.GetTempFileName();
            await using (var filestream = File.Create(filePath))
            {
                await file.CopyToAsync(filestream);
            }
            // get some mediainfo
            MediaInfo.MediaInfoWrapper _mediaInfoWrapper = new MediaInfoWrapper(filePath);

I assume the wrapper does not  understand the linux path. 
Any way to solve this?

*) It looks like the files from the mediainfo package do not make it into to docker image somehow. Maybe related to issue #14, it also returns 'mediainfo file not loaded' when using the logging.

**Comment by yartat** [comment]
I reproduced problem and try to fix it.

**Comment by yartat** [comment]
I prepared ASP.NET Core sample in docker to show how to fix the issue. See /Samples/ApiSample

**Comment by yartat** [comment]
Any feedback on the sample I prepared?

**Comment by hwmaat** [comment]
Got it, thanks for the follow up.
Your second line in the docker file solves the problem!
Until now I manually added mediainfo to the docker image by bashing into the running container and do "apt-get -y install mediainfo".
That also did the job. Just did not think of simply adding that line to the docker file.......

Maybe it is an option to replace the long line you created with simply "apt-get install -y mediainfo"
Will do the job as well?

Regards.
