### ISSUE TITLE
Copy both x86 and x64 MediaInfo.dll to bin

### ISSUE THREAD

**Issue by huan086** [yartat/MP-MediaInfo#3]
My IIS is running x64, thus I choose x64 as target. However, with x64, Entity Framework migration in Visual Studio doesn't work, as VS runs as x86. Would be great if both x86 and x64 DLL are present to have both VS x86 and IIS x64 work (using AnyCPU)

This would require `LoadLibraryEx` in MediaInfo.Wrapper and do it like https://github.com/cschlote/MediaInfoDotNet/blob/master/MediaInfoDotNet/MediaInfoDLL.cs#L206

**Comment by yartat** [comment]
Thanks for the interest in the MediaInfo.Wrapper. I'm checking your changes in closes time.

**Comment by yartat** [comment]
Please, check in the 0.7.93.2

**Comment by huan086** [comment]
One more thing, could you update the MediaInfo.Native target to use CopyToOutputDirectory instead of AfterBuild? AfterBuild does not work when publishing to WebDeploy or Azure Cloud Service.

See
https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/ebd24cf472ea8a320ce865b9a5b90007143d56d5/NuGet/JavaScriptEngineSwitcher.V8.Native.win-x64/build/JavaScriptEngineSwitcher.V8.Native.win-x64.props

https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/ebd24cf472ea8a320ce865b9a5b90007143d56d5/NuGet/JavaScriptEngineSwitcher.V8.Native.win-x86/build/JavaScriptEngineSwitcher.V8.Native.win-x86.props

**Comment by yartat** [comment]
Thanks for the feedback. I will change today evening

**Comment by yartat** [comment]
Sorry for the long wait. Please, check in the 0.7.93.3

**Comment by huan086** [comment]
Thanks so much!

Unfortunately I had trouble associating MediaInfo StreamOrder/ID with ffmpeg stream numbers and have thus switched to ffprobe and parsing it's output :(
