### ISSUE TITLE
AudioCodec has wrong serialization info for wma2

### ISSUE THREAD

**Issue by MrRickwi** [yartat/MP-MediaInfo#30]
In enum AudioCodec, wma2 and wma3 are coded to string wma3. That is in v 21.3.3, the code in the repository seems to be fixed now.

**Comment by MrRickwi** [comment]
Could you release the HEAD as a new beta nuget package? I'm willing to test that in our software.

**Comment by yartat** [comment]
Done.

**Comment by MrRickwi** [comment]
Thanks!
