### ISSUE TITLE
Linux - MediaInfo.dll was not loaded!

### ISSUE THREAD

**Issue by MichaelHochriegl** [yartat/MP-MediaInfo#32]
I'm currently trying to get the MediaInfo.Wrapper.Core up and running but I get the error message `MediaInfo.dll was not loaded!` when I try to use the sample project.

I'm running Fedora 34 and as I can see in the runtimes folder in my bin directory there is no folder for Fedora 34.
I've installed the needed dependencies and MediaInfoLib itself is also installed (MediaInfoLib - v21.03).

I can the mediainfo CLI command just fine.
Could someone please give me any guidance on how to get this running?

**Comment by yartat** [comment]
New version of [MediaInfo.Core.Native](https://www.nuget.org/packages/MediaInfo.Core.Native/21.3.3) is available with support Fedora 34. I prepared new build [MediaInfo.Wrapper.Core](https://www.nuget.org/packages/MediaInfo.Wrapper.Core/21.3.5) with MediaInfo.Core.Native 21.3.3

**Comment by yartat** [comment]
Any news?

**Comment by MichaelHochriegl** [comment]
Sorry for my late reply, been buried in work. I will try to get a test up on running tomorrow and will give you feedback.

**Comment by MichaelHochriegl** [comment]
Works like a charm now, thanks for updating this.
