### ISSUE TITLE
LanguageMediaStream.Default is always false

### ISSUE THREAD

**Issue by srenrd** [yartat/MP-MediaInfo#4]
Hey, I have multiple mkv movies with ac3 audio tracks that has a Default flag. When inspecting them with the MediaInfo program, I can verify that each movie has an ac3 track with the flag set to "Yes". Yet when using your wrapper the default flag aka. LanguageMediaStream.Default always appears as false? From my tests this is a proplem for both video and audio streams.

**Comment by srenrd** [comment]
The problem is that the flags are represented by "Yes" and "No". You are using bool.TryParse for the conversion which will always fail. Solution could be to add a custom bool TryParse method for the flags.

**Comment by yartat** [comment]
Thank you for solution. I will fix this issue for a close time.

**Comment by yartat** [comment]
Was closed in release 18.12
