### ISSUE TITLE
Double values of streams are all wrong on .NET Core 2.2 on non-English Windows installs

### ISSUE THREAD

**Issue by EraYaN** [yartat/MP-MediaInfo#8]
So it just takes the `.` and ignores it making "23.972" -> 23972. There is some culture handling but it's mostly not working since `TryParse` does not fail (return false), but just returns the wrong value. I'm working on some patches to fix this. (And switch the `_englishCulture` to `InvariantCulture`)

**Comment by andrewjswan** [comment]
Same problem, urgent correction needed. :(

**Comment by andrewjswan** [comment]
Same problem:
Video duration      : **61203**.11:53:20
Video frame rate    : **29970**
Audio duration      : **61203**.14:06:40
Audio rate          : **1509000**
But:
Media duration      : 01:28:07.9820000 - Ok!
